server:
  port: 80

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521/xe
    username: hr
    password: hr
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: VARCHAR
  type-aliases-package: com.company.app
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      company:
        boot: DEBUG
        
    
